name = "Minimum + Performance"
author = "Nebula"
version = "1.1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c5f35b2e7a77aee32b6df13440a0d71272dd90e6260fe002f9ec3d8d14a0dd45"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
