name = "Minimum + Performance"
author = "Nebula"
version = "1.1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5d4dd600a6ac44e71fee5205d2fe42f0cf6795cd054faf08a01ed76c4f9c46ef"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
