name = "Recommended"
author = "Nebula"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fbb0e16093cc036d7c5c5afe589562390b1583a32aeb69b5a1b8c241c278e9d8"

[versions]
fabric = "0.14.7"
minecraft = "1.19"
